// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
     
      >
        <nav className="bg-gray-400 py-4">
          <ul className="flex justify-center items-center gap-20">
          <li><Link href="/addTask" className="font-semibold text-gray-800 text-lg">Add a Task</Link></li>
          <li><Link href="/myTasks" className="font-semibold text-gray-800 text-lg">My Tasks</Link></li>
          </ul>
        </nav>

        <div>
          {children}
        </div>

      
      </body>
    </html>
  );
}
